[project]
name = "zaia.app"
version = "0.1.0"
kind = "lib"

[sources]
include = ["src/**/*.z42"]

[dependencies]
"zaia.core"     = "0.1.0"
"zaia.ui"       = "0.1.0"
"zaia.renderer" = "0.1.0"
"zaia.web"      = "0.1.0"
