[project]
name = "zaia.shared"
version = "0.1.0"
kind = "lib"

[sources]
include = ["src/**/*.z42"]

[dependencies]
"zaia.core"    = "0.1.0"
"z42.net"      = "0.1.0"
"z42.json"     = "0.1.0"
"z42.encoding" = "0.1.0"
